"""Half-block orange-cat logo renderer (InvestPilot v0.2.2).

Public API:
- :data:`PALETTE` — palette colors re-exported for tests.
- :data:`ANIMATIONS` — 5-frame small-logo animation names.
- :data:`FRAMES_PER_ANIM` — frames per animation (currently 4).
- :func:`render_big_head` — big logo (32 cells × 18 visual rows).
- :func:`render_small_frame` — single small-logo frame.
- :func:`render_small_static` — current frame per module-level state
  (used as the TUI's per-tick render target).
- :func:`set_small_state` — set state for the static renderer
  (also exposed as ``set_state``).
- :data:`BIG_HEAD_CELLS_W` / :data:`BIG_HEAD_CELLS_H` /
  :data:`SMALL_CELLS_W` / :data:`SMALL_CELLS_H`.

The pixel data is generated by ``tools/build_logos.py`` and stored in
``_logo_assets.py``. Each cell at ``(row, col)`` is rendered with the
half-block characters ``▀`` (top) or ``▄`` (bottom) and Rich markup
``[#hex on #hex]...[/]`` for stacked colors.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from investpilot.interface import _logo_assets

if TYPE_CHECKING:
    pass

PALETTE: tuple[str | None, ...] = _logo_assets.PALETTE
PAL_HEX_LOWER = {idx: c.lower() for idx, c in enumerate(PALETTE) if c is not None}

BIG_HEAD_CELLS_W: int = _logo_assets.BIG_HEAD_CELLS_W
BIG_HEAD_CELLS_H: int = _logo_assets.BIG_HEAD_CELLS_H  # 18 → 36 pixel rows on render

SMALL_CELLS_W: int = _logo_assets.SMALL_CELLS_W
SMALL_CELLS_H: int = _logo_assets.SMALL_CELLS_H  # 9 → 18 pixel rows

ANIMATIONS: tuple[str, ...] = ("wave", "ear", "tail", "blink", "peek")
FRAMES_PER_ANIM: int = 4


def _cell_to_markup(up_idx: int, down_idx: int) -> str:
    """Render a single cell (two pixel rows) to Rich markup.

    Each "cell" is 1 column wide × 2 pixel rows tall. Output is one
    terminal character with appropriate fg / bg.

    - Both transparent → ``" "``.
    - Only top colored → ``▀`` with fg = top.
    - Only bottom colored → ``▄`` with fg = bottom.
    - Both same color → full-block ``█``.
    - Different colors → ``▀`` with ``[fg on bg]`` markup.
    """
    if up_idx == 0 and down_idx == 0:
        return " "
    if up_idx == 0:
        assert PALETTE[down_idx] is not None
        return f"[{PAL_HEX_LOWER[down_idx]}]▄[/]"
    if down_idx == 0:
        assert PALETTE[up_idx] is not None
        return f"[{PAL_HEX_LOWER[up_idx]}]▀[/]"
    upper = PAL_HEX_LOWER[up_idx]
    lower = PAL_HEX_LOWER[down_idx]
    if upper == lower:
        return f"[{upper}]█[/]"
    return f"[{upper} on {lower}]▀[/]"


def _render_grid(rows: tuple[tuple[int, ...], ...], cells_w: int, cells_h: int) -> str:
    """Convert a (cells_h×2 pixel rows) × cells_w grid to markup text."""
    out_lines: list[str] = []
    for cell_y in range(cells_h):
        top = rows[cell_y * 2]
        bot = rows[cell_y * 2 + 1]
        # Both rows have cells_w columns
        line_parts = [_cell_to_markup(top[col], bot[col]) for col in range(cells_w)]
        out_lines.append("".join(line_parts))
    return "\n".join(out_lines)


def render_big_head() -> str:
    """Render the big orange-cat head (32 cells × 18 visual rows)."""
    return _render_grid(_logo_assets.BIG_HEAD, BIG_HEAD_CELLS_W, BIG_HEAD_CELLS_H)


def _validate_anim_frame(name: str, frame_index: int) -> tuple[int, ...]:
    if name not in _logo_assets.SMALL_FRAMES:
        raise ValueError(
            f"unknown animation {name!r}; expected one of {ANIMATIONS}"
        )
    frames = _logo_assets.SMALL_FRAMES[name]
    idx = frame_index % len(frames)
    return frames[idx]


def render_small_frame(name: str, frame_index: int) -> str:
    """Render the small orange-cat mascot for one animation frame.

    Parameters:
        name: animation name (must be in :data:`ANIMATIONS`).
        frame_index: 0-3, taken modulo the frame count.
    """
    rows = _validate_anim_frame(name, frame_index)
    return _render_grid(rows, SMALL_CELLS_W, SMALL_CELLS_H)


# ---------------------------------------------------------------------------
# Module-level state used by the TUI tick loop.
# ---------------------------------------------------------------------------

_state: dict[str, int] = {"anim_idx": 0, "frame_idx": 0}


def get_state() -> tuple[str, int]:
    return ANIMATIONS[_state["anim_idx"] % len(ANIMATIONS)], _state["frame_idx"] % FRAMES_PER_ANIM


def set_small_state(name: str, frame_index: int) -> None:
    """Override the static-renderer state. Mainly for tests."""
    if name not in ANIMATIONS:
        raise ValueError(f"unknown animation {name!r}")
    _state["anim_idx"] = ANIMATIONS.index(name)
    _state["frame_idx"] = frame_index


def advance_state() -> tuple[str, int]:
    """Advance to the next frame; roll over to next animation at end."""
    _state["frame_idx"] += 1
    if _state["frame_idx"] >= FRAMES_PER_ANIM:
        _state["frame_idx"] = 0
        _state["anim_idx"] = (_state["anim_idx"] + 1) % len(ANIMATIONS)
    return get_state()


def render_small_static() -> str:
    """Render the small mascot using the current module state."""
    name, idx = get_state()
    return render_small_frame(name, idx)


# Backwards-compat alias (kept for the test suite naming convenience).
set_state = set_small_state
